x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "10"

# https://docs.gitlab.com/omnibus/docker/README.html#install-gitlab-using-docker-compose
services:
  gitlab-web:
    image: 'gitlab/gitlab-ce:12.5.4-ce.0'
    container_name: gitlab-web
    restart: always
    logging:
      <<: *default-logging
    hostname: "${HOSTNAME_FQDN}"
    environment:
      # https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${HOSTNAME_FQDN}'
        nginx['redirect_http_to_https'] = true

        # https://docs.gitlab.com/omnibus/settings/nginx.html#setting-http-strict-transport-security
        # https://www.nginx.com/blog/http-strict-transport-security-hsts-and-nginx/
        # nginx['hsts_max_age'] = 0  # 0 disable HSTS, for self-signed SSL cert only

        # https://docs.gitlab.com/12.10/ee/administration/pages/index.html#wildcard-domains
        # pages will be available at https://<USER or GROUP>.${HOSTNAME_FQDN}/<REPO>
        pages_external_url 'https://${HOSTNAME_FQDN}'
        pages_nginx['redirect_http_to_https'] = true
        gitlab_pages['inplace_chroot'] = true

        # rather not take over the really ssh port 22 of the host
        # still need for ssh connection to the host for administration
        gitlab_rails['gitlab_shell_ssh_port'] = 2224

        # Only applicable on initial setup, changing these settings
        # after database is created and seeded won't yield any change.
        gitlab_rails['initial_root_password'] = "${INITIAL_ROOT_PASSWORD}"

        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "${SMTP_SERVER}"
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        gitlab_rails['smtp_enable_starttls_auto'] = false
        gitlab_rails['smtp_ssl'] = false
        gitlab_rails['smtp_force_ssl'] = false

    ports:
      - '80:80'
      - '443:443'
      - '2224:22'
    volumes:
      - 'gitlab_config_persistence:/etc/gitlab'
      - 'gitlab_logs_persistence:/var/log/gitlab'
      - 'gitlab_data_persistence:/var/opt/gitlab'
      - '${SSL_CERTIFICATE}:/etc/gitlab/ssl/${HOSTNAME_FQDN}.crt:ro'
      - '${SSL_CERTIFICATE_KEY}:/etc/gitlab/ssl/${HOSTNAME_FQDN}.key:ro'

  gitlab-runner:
    image: 'gitlab/gitlab-runner:v14.7.0'
    container_name: gitlab-runner
    restart: always
    logging:
      <<: *default-logging
    volumes:
      - './config/runner/config.toml:/etc/gitlab-runner/config.toml:rw'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

volumes:
  gitlab_data_persistence:
    external:
      name: gitlab_data_persistence
  gitlab_config_persistence:
    external:
      name: gitlab_config_persistence
  gitlab_logs_persistence:
    external:
      name: gitlab_logs_persistence

# vi: tabstop=8 expandtab shiftwidth=2 softtabstop=2
