version: '2'
services:
  web:
    image: 'gitlab/gitlab-ce:12.5.4-ce.0'
    restart: always
    hostname: "${HOSTNAME_FQDN}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${HOSTNAME_FQDN}'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - 'gitlab_config_persistence:/etc/gitlab'
      - 'gitlab_logs_persistence:/var/log/gitlab'
      - 'gitlab_data_persistence:/var/opt/gitlab'

volumes:
  gitlab_data_persistence:
    external:
      name: gitlab_data_persistence
  gitlab_config_persistence:
    external:
      name: gitlab_config_persistence
  gitlab_logs_persistence:
    external:
      name: gitlab_logs_persistence

# vi: tabstop=8 expandtab shiftwidth=2 softtabstop=2
